import { z } from 'zod';
import { authRoute } from '@/lib/auth-routes';
import { assert, HttpError, id, match, now, one, publicUser, query, rows, session } from '@/lib/server';

export const dynamic = 'force-dynamic';
type RecordRow = Record<string, any>;
const profile = z.object({ name: z.string().trim().min(2).max(100), role: z.enum(['worker', 'business']), city: z.string().trim().max(100), skills: z.string().max(500), bio: z.string().max(2000), experience: z.coerce.number().int().min(0).max(60), expectedPay: z.coerce.number().int().min(0), company: z.string().max(120) });
const job = z.object({ title: z.string().trim().min(5).max(120), description: z.string().trim().min(20).max(5000), category: z.string().trim().min(2).max(100), city: z.string().trim().min(2).max(100), skills: z.string().trim().min(2).max(500), start: z.string().datetime(), duration: z.coerce.number().int().min(1).max(168), budget: z.coerce.number().int().min(100), experience: z.coerce.number().int().min(0).max(60) });

function response(payload: unknown, status = 200) { return Response.json(payload, { status, headers: { 'Cache-Control': 'no-store' } }); }
function error(error: unknown) { if (error instanceof z.ZodError) return response({ error: error.issues[0]?.message || 'Invalid data' }, 400); if (error instanceof HttpError) return response({ error: error.message }, error.status); console.error(error); return response({ error: 'Something went wrong. Please try again.' }, 500); }

async function handle(request: Request) {
  const path = new URL(request.url).pathname.replace(/^\/api\//, '');
  const auth = await authRoute(request, path); if (auth) return auth;
  const user = await session(request) as RecordRow | null;
  if (request.method === 'GET' && path === 'health') return response({ ok: true });
  if (request.method === 'GET' && path === 'me') return response({ user });
  if (request.method === 'GET' && path === 'jobs') { const jobs = await rows<RecordRow>("SELECT j.*, u.name owner_name, u.company FROM jobs j JOIN users u ON u.id=j.owner_id WHERE j.status='open' AND j.start>? ORDER BY j.created_at DESC", now()); return response({ jobs: jobs.map(item => ({ ...item, match: user ? match(item, user) : null })) }); }
  assert(user, 'Sign in to continue.', 401);
  if (request.method === 'POST' && path === 'profile') { const body = profile.parse(await request.json()); if (body.role === 'business') assert(body.company.trim().length > 1, 'Enter your business name.'); await query('UPDATE users SET name=?,role=?,city=?,skills=?,bio=?,experience=?,expected_pay=?,company=? WHERE id=?', body.name, body.role, body.city, body.skills, body.bio, body.experience, body.expectedPay, body.company, user.id).run(); return response({ ok: true }); }
  if (request.method === 'POST' && path === 'jobs') { assert(user.role === 'business' && user.company, 'Complete your business profile before posting.', 403); const body = job.parse(await request.json()); assert(Date.parse(body.start) > Date.now(), 'Start time must be in the future.'); const jobId = id(); await query('INSERT INTO jobs(id,owner_id,title,description,category,city,skills,start,duration,budget,experience,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)', jobId, user.id, body.title, body.description, body.category, body.city, body.skills, body.start, body.duration, body.budget, body.experience, now()).run(); return response({ id: jobId }, 201); }
  if (request.method === 'POST' && /^jobs\/[^/]+\/apply$/.test(path)) { const jobId = path.split('/')[1]; const body = z.object({ note: z.string().trim().min(10).max(2000) }).parse(await request.json()); const target = await one<RecordRow>('SELECT * FROM jobs WHERE id=?', jobId); assert(target && target.status === 'open' && Date.parse(target.start) > Date.now(), 'This job is not accepting applications.', 409); assert(user.role === 'worker' && user.id !== target.owner_id, 'Only workers can apply.', 403); await query("INSERT INTO applications(id,job_id,worker_id,note,created_at) VALUES(?,?,?,?,?) ON CONFLICT(job_id,worker_id) DO UPDATE SET status='applied', note=excluded.note", id(), jobId, user.id, body.note, now()).run(); return response({ ok: true }); }
  if (request.method === 'POST' && /^applications\/[^/]+\/hire$/.test(path)) { const applicationId = path.split('/')[1]; const application = await one<RecordRow>('SELECT a.*,j.owner_id,j.status job_status FROM applications a JOIN jobs j ON j.id=a.job_id WHERE a.id=?', applicationId); assert(application && application.owner_id === user.id, 'Only the business can hire.', 403); assert(application.job_status === 'open' && application.status === 'applied', 'This application cannot be hired.', 409); const hired = await query("UPDATE jobs SET status='hired',worker_id=? WHERE id=? AND status='open' RETURNING id", application.worker_id, application.job_id).first(); assert(hired, 'This job has already been filled.', 409); await query("UPDATE applications SET status=CASE WHEN id=? THEN 'hired' ELSE 'rejected' END WHERE job_id=? AND status='applied'", applicationId, application.job_id).run(); return response({ ok: true }); }
  if (request.method === 'GET' && path === 'dashboard') { const jobs = await rows<RecordRow>('SELECT j.*,u.company,u.name owner_name FROM jobs j JOIN users u ON u.id=j.owner_id WHERE j.owner_id=? OR j.worker_id=? OR j.id IN (SELECT job_id FROM applications WHERE worker_id=?) ORDER BY j.created_at DESC', user.id, user.id, user.id); const applications = await rows<RecordRow>('SELECT a.*,u.name worker_name,u.skills,u.city FROM applications a JOIN users u ON u.id=a.worker_id JOIN jobs j ON j.id=a.job_id WHERE a.worker_id=? OR j.owner_id=? ORDER BY a.created_at DESC', user.id, user.id); return response({ jobs, applications }); }
  if (request.method === 'POST' && path === 'jobs/complete') { const body = z.object({ jobId: z.string() }).parse(await request.json()); const target = await one<RecordRow>('SELECT * FROM jobs WHERE id=?', body.jobId); assert(target && target.owner_id === user.id && target.status === 'hired', 'Only the hiring business can complete this job.', 403); await query("UPDATE jobs SET status='completed' WHERE id=?", body.jobId).run(); await query("INSERT INTO payments(job_id,amount,commission,status,created_at) VALUES(?,?,?,?,?)", body.jobId, target.budget, Math.round(target.budget * .05), 'pending', now()).run(); return response({ ok: true }); }
  if (request.method === 'GET' && path === 'admin') { assert(user.isAdmin, 'Administrator access required.', 403); return response({ users: (await rows<RecordRow>('SELECT * FROM users ORDER BY created_at DESC LIMIT 200')).map(publicUser), jobs: await rows('SELECT * FROM jobs ORDER BY created_at DESC LIMIT 200'), payments: await rows('SELECT p.*,j.title FROM payments p JOIN jobs j ON j.id=p.job_id ORDER BY p.created_at DESC LIMIT 200') }); }
  throw new HttpError(404, 'Not found.');
}
async function dispatch(request: Request) { if (request.method === 'POST' && !request.headers.get('content-type')?.includes('application/json')) return response({ error: 'JSON required' }, 415); try { return await handle(request); } catch (caught) { return error(caught); } }
export const GET = dispatch; export const POST = dispatch;
