import { useState } from 'react';
import { ArrowRight, ShieldCheck, Upload, X, VenetianMask, Check, Mail, Flag } from 'lucide-react';
import { api, categories, communities } from './lib';
import { Field, FormError } from './ui';

export function AuthForm({ config, onSuccess }) {
  const [name,setName]=useState(''),[email,setEmail]=useState(''),[code,setCode]=useState(''),[step,setStep]=useState(1),[notice,setNotice]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  async function submit(e){e.preventDefault();setBusy(true);setError('');try{if(step===1){const r=await api('/auth/request',{method:'POST',body:{name,email}});setNotice(r.message);setStep(2);}else{const r=await api('/auth/verify',{method:'POST',body:{email,code}});onSuccess(r.user);}}catch(e){setError(e.message);}finally{setBusy(false);}}
  async function useDemo(){setBusy(true);setError('');try{const r=await api('/auth/demo',{method:'POST'});onSuccess(r.user);}catch(e){setError(e.message);}finally{setBusy(false);}}
  return <div className="form-body"><div className="auth-icon"><ShieldCheck size={28}/></div><h3 className="form-heading">Your campus. Your people.</h3><p className="muted">Sign in or join with any email address. One community, a little more trust.</p><form onSubmit={submit} className="stack">{step===1?<><Field label="Your name"><input required maxLength={60} autoComplete="name" value={name} onChange={e=>setName(e.target.value)} placeholder="Alex Morgan"/></Field><Field label="Email address" hint="We will send a six-digit code to this inbox."><input required type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com"/></Field></>:<><p className="info-note"><Mail size={18}/>{notice}</p><Field label="Six-digit verification code"><input required pattern="[0-9]{6}" inputMode="numeric" autoComplete="one-time-code" maxLength={6} value={code} onChange={e=>setCode(e.target.value)} placeholder="000000"/></Field><button type="button" className="text-btn" onClick={()=>{setStep(1);setCode('');}}>Change email or request a new code</button></>}<FormError error={error}/><button disabled={busy} className="btn primary full">{busy?'Please wait…':step===1?'Continue with email':'Verify & join campus'}<ArrowRight size={17}/></button></form>{config.demo&&<><div className="divider-word">explore the local demo</div><button disabled={busy} className="btn full" onClick={useDemo}>Enter as a demo student<ArrowRight size={17}/></button><p className="fine-print">Sample campus and accounts. Demo access is disabled in production.</p></>}</div>;
}

export function ListingForm({onSuccess}){
  const [form,setForm]=useState({title:'',description:'',price:'',category:'Books',condition:'Good',location:'',kind:'Sell',semester:false});
  const [images,setImages]=useState([]),[uploading,setUploading]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const set=(key,value)=>setForm(f=>({...f,[key]:value}));
  async function upload(e){const files=Array.from(e.target.files||[]);e.target.value='';if(images.length+files.length>4){setError('Choose up to 4 photos.');return;}setUploading(true);setError('');try{for(const file of files){if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>5*1024*1024)throw new Error('Use JPEG, PNG or WebP photos under 5 MB.');const data=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=()=>reject(new Error('Could not read the photo.'));r.readAsDataURL(file);});const result=await api('/uploads',{method:'POST',body:{data}});setImages(prev=>[...prev,result.url]);}}catch(e){setError(e.message);}finally{setUploading(false);}}
  async function submit(e){e.preventDefault();setBusy(true);setError('');try{await api('/listings',{method:'POST',body:{...form,price:form.kind==='Sell'?Number(form.price):0,images}});onSuccess();}catch(e){setError(e.message);}finally{setBusy(false);}}
  return <form className="form-body stack" onSubmit={submit}><p className="muted">A good photo and a few honest details go a long way.</p><div className="segmented">{['Sell','Free','Exchange'].map(k=><button type="button" key={k} className={form.kind===k?'active':''} onClick={()=>set('kind',k)}>{k==='Free'?'Give away':k}</button>)}</div><div className="upload-grid">{images.map(url=><div className="upload-preview" key={url}><img src={url} alt="Uploaded item"/><button type="button" className="icon-btn" onClick={()=>setImages(images.filter(i=>i!==url))} aria-label="Remove photo"><X size={16}/></button></div>)}{images.length<4&&<label className="upload-box"><Upload size={23}/><strong>{uploading?'Uploading…':'Add photos'}</strong><span>Up to 4 · 5 MB each</span><input type="file" multiple accept="image/jpeg,image/png,image/webp" disabled={uploading} onChange={upload}/></label>}</div><Field label="Item name"><input required maxLength={100} placeholder="e.g. Casio scientific calculator" value={form.title} onChange={e=>set('title',e.target.value)}/></Field><div className="form-row"><Field label="Category"><select value={form.category} onChange={e=>set('category',e.target.value)}>{categories.map(c=><option key={c}>{c}</option>)}</select></Field><Field label="Condition"><select value={form.condition} onChange={e=>set('condition',e.target.value)}>{['Like new','Good','Fair'].map(c=><option key={c}>{c}</option>)}</select></Field></div>{form.kind==='Sell'&&<Field label="Price (₹)"><input required type="number" min="1" max="10000000" step="1" value={form.price} onChange={e=>set('price',e.target.value)} placeholder="0"/></Field>}<Field label="Description"><textarea required minLength={10} maxLength={3000} rows={4} value={form.description} onChange={e=>set('description',e.target.value)} placeholder="Tell us about the item, any signs of wear, and what’s included."/></Field><Field label="Meetup location on campus"><input required maxLength={100} value={form.location} onChange={e=>set('location',e.target.value)} placeholder="e.g. Library square, North hostel"/></Field><label className="check-row"><input type="checkbox" checked={form.semester} onChange={e=>set('semester',e.target.checked)}/><span>Include in the Semester-End Marketplace</span></label><FormError error={error}/><button className="btn primary full" disabled={busy||uploading}>{busy?'Publishing…':'Publish listing'}<ArrowRight size={18}/></button></form>;
}
export function PostForm({onSuccess,wanted=false,user}){
  const [title,setTitle]=useState(''),[body,setBody]=useState(''),[community,setCommunity]=useState(wanted?'Want to buy':'Campus life'),[anonymous,setAnonymous]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState('');
  async function submit(e){e.preventDefault();setBusy(true);setError('');try{await api('/posts',{method:'POST',body:{title,body,community,anonymous}});onSuccess();}catch(e){setError(e.message);}finally{setBusy(false);}}
  return <form className="form-body stack" onSubmit={submit}><p className="muted">A question, a campus thought, or a new connection. Start here.</p><Field label="Community"><select value={community} onChange={e=>setCommunity(e.target.value)}>{communities.map(c=><option key={c}>{c}</option>)}</select></Field><Field label="Title"><input required maxLength={180} placeholder={wanted?'What are you looking for?':'What’s on your mind?'} value={title} onChange={e=>setTitle(e.target.value)}/></Field><Field label="Your post"><textarea required minLength={5} maxLength={5000} rows={5} placeholder="Share a little more…" value={body} onChange={e=>setBody(e.target.value)}/></Field><label className="anonymous-choice"><VenetianMask size={26}/><span><strong>Post anonymously</strong><small>{anonymous?`You’ll appear as ${user.alias}`:`You’ll appear as ${user.name}`}</small></span><input type="checkbox" checked={anonymous} onChange={e=>setAnonymous(e.target.checked)}/></label><p className="fine-print">Your identity is hidden from other students, but linked to your account for moderation. Please be kind and avoid sharing personal information.</p><FormError error={error}/><button disabled={busy} className="btn primary full">{busy?'Publishing…':'Post to campus'}<ArrowRight size={18}/></button></form>;
}
export function ReportForm({target,onSuccess}){
  const [reason,setReason]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
  async function submit(e){e.preventDefault();setBusy(true);try{await api('/reports',{method:'POST',body:{...target,reason}});onSuccess();}catch(e){setError(e.message);}finally{setBusy(false);}}
  return <form className="form-body stack" onSubmit={submit}><p className="info-note"><Flag size={20}/>Your report is private and helps keep campus welcoming.</p><Field label="What seems wrong?"><textarea required minLength={5} maxLength={1000} rows={5} value={reason} onChange={e=>setReason(e.target.value)} placeholder="Describe the issue so a moderator can review it."/></Field><FormError error={error}/><button disabled={busy} className="btn primary">{busy?'Submitting…':'Submit report'}<Check size={18}/></button></form>;
}
